### ISSUE TITLE
Error while using Tableau with TabPy

### ISSUE THREAD

**Issue by mfoote4** [tableau/TabPy#14] opened 2016-12-13 21:47 UTC
Hi!

I currently have my TabPy server running on the localhost under port 9004. However, when I try to drag a pill containing a python script, I receive these comments and errors from the command line:
![error](https://cloud.githubusercontent.com/assets/14317792/21191105/55db55e8-c1e1-11e6-9ed5-692da631c15f.PNG)

the pill contains this script:
![error1](https://cloud.githubusercontent.com/assets/14317792/21191100/535e87cc-c1e1-11e6-8637-7284eb34c1d9.PNG)

Additionally, Tableau gives me this error:
![error2](https://cloud.githubusercontent.com/assets/14317792/21160407/f9f4d5fa-c141-11e6-9e78-406f32aff45c.PNG) 
and in show details it says invalid JSON.

If you can help me with this issue, it would be greatly appreciated! 

Thanks!

**Comment by BBeran** [comment] 2016-12-20 22:47
Hi,
Can you try changing your addressing settings for the calculation. For example if you have [Date] as a dimension in the view, right click on the pill for this calculation in your sheet and select Edit Table Calculation from the context menu and then select Specific Dimensions from the list then check the box next to Date.  If you want to send all of your data at once to Python, you may want to check all of the boxes in that list. Anything unchecked will be treated as a partition meaning Tableau will make a separate call with the data within that partition. E.g. if you want to compute correlation per product line, you would want to uncheck the product line box. My guess is that, in this case things are partitioned in a way correlation gives a divide by zero error.

Thanks,

~ Bora

**Comment by BBeran** [comment] 2017-01-24 01:12
Resolving as this scenario is confirmed to work with correct table calculation settings and error message in the console shows that degrees of freedom <= 0 which indicates that this is caused by incorrect table calculation settings resulting in sending one point at a time causing n - 2 = -1 degrees of freedom. The solution provided in the earlier message solves this problem.

**Closed by BBeran** 2017-01-24 01:12 UTC
