### ISSUE TITLE
Endpoint Connection Refused

### ISSUE THREAD

**Issue by Fermaldehyde** [tableau/TabPy#70] opened 2017-11-17 16:57 UTC
Hey Bora,

I've been following along the Breast Cancer example, but using some of my own data to try to deploy one of our own algorithms. However, when I run the connection.deploy() command I get:

**ResponseError:** (502) <HEAD><TITLE>Connection refused</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Connection refused</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: Connection refused</B></FONT>
<HR>

</BODY>

I can connect to the Tabpy Server in Tableau, and if I navigate to the localhost and port on my browser I see the large Tableau logo. The error occurs during the get_endpoints() function as part of deploy.

I thought it might be our company firewall at first, but my environment variables are set and everything else seems to be working just fine. Not ruling it out- just not sure how to solve it if it was.

Any idea what could be causing this?

**Comment by BBeran** [comment] 2017-12-21 21:15
Are you deploying from one machine to another by any chance? There is a known issue with cross system deploy. Can you try running the deploy command on the same machine as the one running TabPy i.e. deploy on localhost?

**Comment by nmannheimer** [comment] 2018-06-19 00:09
Hi @Fermaldehyde,

I'm going to close this issue for now, but feel free to reopen it if the issue is persisting.

**Closed by nmannheimer** 2018-06-19 00:09 UTC
