### ISSUE TITLE
Unable to start Taby server on Windows 10

### ISSUE THREAD

**Issue by ramaraju3** [tableau/TabPy#20] opened 2017-02-18 22:35 UTC
I'm getting this error whenever I click on external connection, "RServe: An error has occurred during connection to localhost:9004: No connection could be made because the target machine actively refused it ExtSvc: Couldn't connect to server"
I tried all possible ways, I'm using Python 2.7. 
Kindly advice on this.
![capture](https://cloud.githubusercontent.com/assets/18431491/23097397/917fafb0-f600-11e6-97a2-5de234d69bed.JPG)

**Comment by ramaraju3** [comment] 2017-02-18 22:42
![capture](https://cloud.githubusercontent.com/assets/18431491/23097432/960aab74-f601-11e6-8619-05a69b1b3ac7.JPG)

**Comment by BBeran** [comment] 2017-02-19 08:17
Hi,
Were you able to install Anaconda successfully? Since there are two screenshots I am confused.

If you're able to install, did you try starting up TabPy after you activated the environment.  You will see a startup.bat in tabpy_server folder under your Anaconda's site-packages. You need to run startup.bat before trying to connect from Tableau.

Thanks,

Bora

**Comment by ramaraju3** [comment] 2017-02-19 19:03
Thanks Bora for getting back to me.
Yes, I've Anaconda installed. This is the error that I'm getting when i try to run startup.bat or startup.py.
![capture](https://cloud.githubusercontent.com/assets/18431491/23105383/3bf33f1a-f6ac-11e6-88f9-4df14aeb607f.JPG)

Thank you,
Rama

**Comment by BBeran** [comment] 2017-02-19 22:20
The issue is that your active conda environment is Tableau-Python-Server but tabpy is installed in the default environment.  If it were under Tableau-Python-Server the path in the screenshot would include Anaconda2\envs\Tableau-Python-Server\lib\site-packages\tabpy_server

Given you already have the environment created, following the installation steps listed here and then starting it should solve the problem.

https://github.com/tableau/TabPy/blob/master/server.md#manual-installation

**Comment by ramaraju3** [comment] 2017-02-19 22:49
I tried it but I was not able to create the environment. I'm a noob here, so, this is quite confusing for me. 
![create env](https://cloud.githubusercontent.com/assets/18431491/23107453/a1bd4b32-f6cb-11e6-824d-453a5e0c3e75.JPG)
![capture](https://cloud.githubusercontent.com/assets/18431491/23107454/a1c05f66-f6cb-11e6-97f8-76d223288290.JPG)

Is there any way i can start everything from beginning?

**Comment by BBeran** [comment] 2017-02-21 22:20
Looks like Anaconda didn't install properly due to an issue with Anaconda installer.

I would suggest uninstalling Anaconda you currently have, downloading the latest installer from their website, installing it again and then following the manual install instructions listed in my earlier message.

**Comment by BBeran** [comment] 2017-02-25 04:24
I am resolving the issue at this point since there isn't anything I can do to help. I updated TabPy recently such that it can run without Anaconda. You can try to install it without Anaconda as well if you like by simply doing

```Batchfile
pip install tabpy-server
```
in your command line. You don't even have to download a zip file from GitHub.

It will also work on both Python 2.7 and 3.x now.

Thanks,

Bora

**Closed by BBeran** 2017-02-25 04:24 UTC

**Comment by KriAga** [comment] 2018-03-19 13:47
I am working on Windows 10 and have installed Anaconda and also have the tabpy-server and tabpy-client packages successfully installed on my Tableau-Python-Server environment.
![capture](https://user-images.githubusercontent.com/20995709/37593930-c90ee494-2b99-11e8-9962-ba349e786c4d.PNG)
![capture](https://user-images.githubusercontent.com/20995709/37594028-1342e83a-2b9a-11e8-83ae-bab4e5aad120.PNG)
![1](https://user-images.githubusercontent.com/20995709/37594036-172d3fa4-2b9a-11e8-846e-2295d1ff7008.PNG)

Please let me know where I am wrong? Is there some minor error coz I have already tried redoing the whole process twice.

Thank you!

**Comment by KriAga** [comment] 2018-11-23 10:50
I had solved it earlier but did not post it. Thanks anyways! :grinning:
