### ISSUE TITLE
Unable to startup on Ubuntu xenial with current build

### ISSUE THREAD

**Issue by leightonium** [tableau/TabPy#254] opened 2019-04-10 11:57 UTC
https://github.com/tableau/TabPy/blob/00664c72a9c23c92c6fa0561d1621b48212715a2/startup.sh#L12
this should be python3 as python and python3 are not interchangeable. 

fixing this, and then script errors with what looks to be a path issue:
root@2c04ec932ade:/TabPy# ./startup.sh
Checking for presence of Python in the system path variable.
Setting TABPY_ROOT to current working directory.
Installing TabPy-server requirements.
Read the logs at /TabPy/tabpy-server/install.log

Starting TabPy server...
Using default parameters.
Traceback (most recent call last):
  File "tabpy-server/tabpy_server/tabpy.py", line 2, in <module>
    from tabpy_server.app.app import TabPyApp
ModuleNotFoundError: No module named 'tabpy_server.app'

**Comment by leightonium** [comment] 2019-04-10 12:42
By changing to ubuntu bionic the application appears to load, we have set a configuration to use port 8888. Then the application errors when it receives it's first http request:

Starting TabPy server...
2019-04-10,12:38:10 [INFO] (app.py:app:217): Loading state from state file /TabPy/tabpy-server/tabpy_server/state.ini
2019-04-10,12:38:10 [INFO] (app.py:app:242): Password file is not specified
2019-04-10,12:38:10 [INFO] (app.py:app:89): Initializing TabPy...
2019-04-10,12:38:10 [DEBUG] (selector_events.py:selector_events:65): Using selector: EpollSelector
2019-04-10,12:38:10 [INFO] (callbacks.py:callbacks:44): Initializing TabPy Server...
2019-04-10,12:38:10 [INFO] (app.py:app:92): Done initializing TabPy.
2019-04-10,12:38:10 [INFO] (callbacks.py:callbacks:65): Initializing models...
2019-04-10,12:38:10 [INFO] (app.py:app:85): Web service listening on port 8888
2019-04-10,12:40:02 [ERROR] (http1connection.py:http1connection:55): Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python3.6/dist-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 2195, in finish
    self.execute()
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 2215, in execute
    **self.handler_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 194, in __init__
    self.initialize(**kwargs)
TypeError: initialize() got an unexpected keyword argument 'app'

**Comment by 0golovatyi** [comment] 2019-04-10 16:02
@leightonium What Tornado version do you use?

**Comment by leightonium** [comment] 2019-04-10 16:17
It's in a docker container, and pip3 installs tornado==5.1.1

**Comment by 0golovatyi** [comment] 2019-04-10 18:52
@leightonium Yes, Tornado 5.1.1 is what we want to see.

Where is the TabPy you are running from? The latest master branch, or some zip file (which one)? I am asking to try to reproduce.

**Comment by leightonium** [comment] 2019-04-11 09:21
/TabPy
the dockerfile has: RUN git clone https://github.com/tableau/TabPy.git
and this places the repo in /TabPy

**Comment by johng42** [comment] 2019-04-11 16:28
Ubuntu 16.04 ships with Python 3.5 and TabPy requires 3.6.5.

There are 2 solutions for this - both of which are, unfortunately, not trivial to implement.
1. Upgrade to 18.04.  This is the tested Ubuntu config : https://github.com/tableau/TabPy/blob/master/docs/server-configurations.md
2. Install Python 3.6.5+.  Because of the way Ubuntu ships with 3.5, this requires building from source - again, not trivial.

**Comment by leightonium** [comment] 2019-04-15 15:06
@johng42 in my 2nd comment I resolved the initial problem by using Ubuntu Bionic, but this leads to a new error which i am hoping @0golovatyi will be able to reproduce. thanks!

**Comment by 0golovatyi** [comment] 2019-04-15 15:52
@leightonium I tried but wasn't able to. At the moment we only can afford some OS/Python configurations, unfortunately running TabPy in Docker container is not one of them. 

Could you point me to the container you are using? In case there's some spare time I can look at it.

**Comment by leightonium** [comment] 2019-04-15 20:22
The container I am using is an internal build, but I have spun up a ubuntu bionic server and used the docker image ubuntu:latest. This container has the same issue, TabPy server starts but errors on first http call.
here is my dockerfile:

FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    python3.6 \
    python3-pip \
     curl && \
     apt-get clean

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1

RUN git clone https://github.com/tableau/TabPy.git

RUN pip3 install configparser
RUN pip3 install backports_abc cloudpickle decorator future genson
RUN pip3 install jsonschema~=2.3.0 mock numpy python-dateutil
RUN pip3 install requests singledispatch simplejson six tornado==5.1.1
RUN pip3 install Tornado-JSON urllib3

RUN cd /TabPy/tabpy-server/ && \
    python3 setup.py install
RUN cd /TabPy/tabpy-tools && \
    python3 setup.py install

EXPOSE 9004

COPY ./docker-entrypoint.sh /
CMD /docker-entrypoint.sh

and my docker-entrypoint.sh:

cd /TabPy
TABPY_ROOT=$PWD
echo Starting TabPy server...
SAVE_PYTHONPATH=$PYTHONPATH
export PYTHONPATH=${TABPY_ROOT}/tabpy-server:${TABPY_ROOT}/tabpy-tools:$PYTHONPATH
echo $TABPY_ROOT
echo $PYTHONPATH
python3 tabpy-server/tabpy_server/tabpy.py

**Comment by leightonium** [comment] 2019-04-16 20:42
This is not a docker issue. I can reproduce the error on a bionic server.
1. build a ubuntu bionic vm using the 18.04.2-live-server iso
2. ssh into it
3. sudo apt-get update && sudo apt-get upgrade
4. git clone https://github.com/tableau/TabPy.git
5. cd TabPy
6. sudo ./startup.sh
7. fails because of line 12 (my 1st comment). Fix to python3
8. sudo ./startup.sh
9. fails because pip3 is not installed
10. sudo apt-get install python3-pip 
11.  sudo ./startup.sh
12. TabPy server starts up on port 9004
13. start another ssh session into same host
14. curl localhost:9004
15. first ssh session running TabPy now has the error message as above.

**Comment by 0golovatyi** [comment] 2019-04-17 18:41
@leightonium I got it, thanks for the information! The issue you see is TabPy failing to serve a request for when a method is not provided. While it is a bug which I'll prepare a fix for soon this is not how Tableau calls TabPy. If you try `curl localhost:9004/info` you'll see a valid response. And Tableau products call `/evaluate` method with script and data as described on https://github.com/tableau/TabPy/blob/master/docs/server-rest.md.

**Comment by leightonium** [comment] 2019-04-23 09:48
ah ha! thank you, yes /info is showing a valid response.
Previously we got a tableau logo on the / page. Our docker monitoring system needs a url for a health check and is expecting a http 200 result. So if i change the monitoring url or wait for your fix I should be good to go. Thank you for getting to the bottom of this. (and remember to fix the startup.sh line 12 to use python3 !)

**Comment by 0golovatyi** [comment] 2019-04-23 15:52
@leightonium For using `python3` it is not a fix which will work for all the system - as we discovered so far there are differences specifically in how preinstalled or manually installed Python3 is available to a user on Linux. There were cases when Python3 is installed but is available with `python` command and `python3` is "unknown".

**Comment by leightonium** [comment] 2019-04-23 16:04
OK then you need to code for both situations then.
Python3 is installed but is available with python command and python3 is "unknown".
Python3 is installed but is not available with python command and python is "unknown".

**Comment by 0golovatyi** [comment] 2019-04-29 18:15
The issue should be fixed with the latest release - https://github.com/tableau/TabPy/releases/tag/v.0.4.1

**Closed** 2019-05-05 16:24 UTC
